function linode-desktop
  # passwd file is generated by running `vncpasswd`, which is
  # part of the vncserver package.
  xtigervncviewer localhost:1 -FullScreen -PasswordFile=/home/dsicilia/.vnc/passwd
  # xtightvncviewer localhost:1 -passwd ~/.vnc/passwd
end