#!/bin/bash
# ╔═════════════════════════════════════════════════════════════╗
# ║                        Dotfile Sync                         ║
# ╚═════════════════════════════════════════════════════════════╝
# Change to Script Folder
script_dir=$(dirname $0)
cd $script_dir || { echo 'error changing directory.'; exit 1; }

source scripts/utils.sh

# Pull in any changes from the repo.
msg 'Updating files...'
git pull --quiet origin master; check 'update dot files'

msg 'Updating submodules...'
git submodule update --init --quiet; check 'update submodules'

msg 'Applying changes...'
# Apply any new changes to the environment.
bash scripts/setup.sh "$@"; check 'run setup script'

[[ "$(uname)" =~ Linux ]] && {
    # Install per-user fonts.
    bash scripts/fonts.sh; check 'install fonts'
}

reload_tmux() {
    # Reload tmux.conf.
    msg 'Reloading tmux.conf...'
    tmux source-file ~/.tmux.conf
    tmux display-message "Config reloaded."
}

# Reload tmux before and after installing plugins.
reload_tmux

# Install/Refresh tmux plugins
tpm="dot/tmux/plugins/tpm"
$tpm/bin/install_plugins; check 'install tmux plugins'
$tpm/bin/update_plugins all; check 'update tmux plugins'

reload_tmux

msg 'Finished.'
# Exit with success
true
