#!/bin/bash
# ╔═════════════════════════════════════════════════════════════╗
# ║                           bashrc                            ║
# ╚═════════════════════════════════════════════════════════════╝
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

[[ -f /etc/bashrc ]] && source /etc/bashrc

set -o noclobber
set -o pipefail

# ╔═════════════════════════════════════════════════════════════╗
# ║                           Aliases                           ║
# ╚═════════════════════════════════════════════════════════════╝
alias t="tree      -C -A"
alias mv="mv -i"
alias ls="ls -h --color=auto"
alias ll="ls -l"
alias df="df -Ph"
alias grep="grep --exclude-dir=.svn --exclude-dir=.stack-work --exclude-dir=.git --color=auto"
alias egrep="egrep --color=auto"
alias clip='sed -r "s/\t/    /g; s/(.{0,$COLUMNS}).*/\1/g"'
alias tmux='tmux -2'

# ╔═════════════════════════════════════════════════════════════╗
# ║                          Functions                          ║
# ╚═════════════════════════════════════════════════════════════╝
source ~/.bash/utils

# ╔═════════════════════════════════════════════════════════════╗
# ║                          Variables                          ║
# ╚═════════════════════════════════════════════════════════════╝
export PS1="\$? [\u@\h \W]$ "
export PATH=~/bin:~/opt/bin:~/.local/bin:$PATH
export LD_LIBRARY_PATH=~/lib
export GREP_COLORS="mt=01;32"
export EDITOR=vim
# This is so that we don't have windows popping up asking for passwords
unset  SSH_ASKPASS

# ╔═════════════════════════════════════════════════════════════╗
# ║                            Local                            ║
# ╚═════════════════════════════════════════════════════════════╝
[[ -f ~/.bashrclocal ]] && source ~/.bashrclocal
