#!/bin/bash
none() {
    #echo '??'
    exit 0
}

os=$(uname)

if [[ "$os" == Linux ]]; then
    which upower &>/dev/null || none

    dev=$(upower -e 2>/dev/null | grep BAT)
    [[ -z "$dev" ]] && none

    percentage=$(upower -i $dev 2>/dev/null | awk '/percentage/ { print $2 }' | tr -d '%')
else
    # Assume OSX
    percentage=$(pmset -g batt | grep InternalBattery-0 | awk '{print $3}' | tr -d '%;')
fi

[[ -z "$percentage" ]] && none

# If we are fully charged then don't display anything.
(( percentage > 95 )) && exit 0

bg=234

(( percentage <= 10 )) && {
    fg=255 # white
    bg='196' # red
    prefix='BATTERY LOW: '
}

(( percentage >  10 )) && fg=196 # red
(( percentage >= 20 )) && fg=226 # yellow
(( percentage >= 40 )) && fg=202 # orange
(( percentage >= 80 )) && fg=112 # green

echo -ne "#[fg=colour$fg,bg=colour$bg]$prefix$percentage%"
