#!/bin/bash
none() {
    #echo '??'
    exit 0
}

which upower &>/dev/null || none

dev=$(upower -e 2>/dev/null | grep BAT)
[[ -z "$dev" ]] && none

percentage=$(upower -i $dev 2>/dev/null | awk '/percentage/ { print $2 }' | tr -d '%')
[[ -z "$percentage" ]] && none

# If we are fully charged then don't display anything.
(( percentage > 95 )) && exit 0

bg=235

(( percentage <= 12 )) && {
    fg=255 # white
    bg='196' # red
    prefix='BATTERY LOW: '
}

(( percentage >  12 )) && fg=196 # red
(( percentage >= 40 )) && fg=226 # yellow
(( percentage >= 80 )) && fg=112 # green

echo -ne "#[fg=colour$fg,bg=colour$bg]$prefix$percentage%"
